# Security OAuth
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1003506809566-3r51uu3n6912evoh44728i2torj5ksnp.apps.googleusercontent.com
            clientSecret: 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
          #        facebook:
          #          clientId: '{페이스북 client-id}'
          #          clientSecret: '{페이스북 client-secret}'
          #        naver:
          #          clientId: '{네이버 client-id}'
          #          clientSecret: '{네이버 client-secret}'
          kakao:
            clientId: b1be16f6afb8ff6bb84ccc9297947ae4
            clientSecret: zAaTNjoBiVs30pUSVAqm8afHfWgd9r8H

