# Security OAuth
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId:
            clientSecret:
          #        facebook:
          #          clientId: '{페이스북 client-id}'
          #          clientSecret: '{페이스북 client-secret}'
          #        naver:
          #          clientId: '{네이버 client-id}'
          #          clientSecret: '{네이버 client-secret}'
          kakao:
            clientId:
            clientSecret:

