--- # local
--- #local 환경
spring:
  profiles:
    group:
      "local" : "default, security, local-core"


--- #dev 환경
spring:
  profiles:
    group:
      "develop" : "default, security,develop-core"

--- #api 환경

spring:
  profiles:
    group:
      "release" : "default, security,release-core"



